"""create commerce sessions

Revision ID: 7c5b5b8e074b
Revises: 
Create Date: 2026-09-03 17:18:08.398394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5b5b8e074b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commerce_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('cart_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_commerce_sessions_thread_id'), 'commerce_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_commerce_sessions_user_id'), 'commerce_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commerce_sessions_user_id'), table_name='commerce_sessions')
    op.drop_index(op.f('ix_commerce_sessions_thread_id'), table_name='commerce_sessions')
    op.drop_table('commerce_sessions')
    # ### end Alembic commands ###
